backstage:
  image:
    tag: "1.36.1"

  appConfig:
    app:
      title: Platform Backstage
      baseUrl: ""
    backend:
      baseUrl: ""
      cors:
        origin: ""
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      auth:
        keys:
          - secret: insecure-dev-key-change-me
        dangerouslyDisableDefaultAuthPolicy: true
    auth:
      environment: development
      providers:
        guest: {}
    permission:
      enabled: false
    notifications:
      enabled: false
    techdocs:
      builder: local
      generator:
        runIn: local
      publisher:
        type: local
    catalog:
      locations: []
    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}
